name: Release

on:
  push:
    branches: 
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare files
        run: |
          mkdir -p ".release/switch/.overlays/OC-Suite Wizard"
          cp -r ./* ".release/switch/.overlays/OC-Suite Wizard"
          cd .release
          zip -r "OC-Suite-Wizard.zip" switch

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: ".release/OC-Suite-Wizard.zip"
